name       : kdiagram
version    : 2.6.1
release    : 2
source     :
    - https://download.kde.org/stable/kdiagram/2.6.1/kdiagram-2.6.1.tar.xz : bde71ca5ef70b3077696d56b24e0e1f69ae255c0bf7bf453e9596afdd25dcdb0
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Powerful libraries (KChart, KGantt) for creating business diagrams.
description: |
    Powerful libraries (KChart, KGantt) for creating business diagrams.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules

setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
