name       : kdiagram
version    : 2.7.0
release    : 3
source     :
    - https://cdn.download.kde.org/stable/kdiagram/2.7.0/kdiagram-2.7.0.tar.xz : 63a2eabfa1554ceb1d686d5f17ed6308139b6d9155aaf224e0309585b070fbdd
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Powerful libraries (KChart, KGantt) for creating business diagrams.
description: |
    Powerful libraries (KChart, KGantt) for creating business diagrams.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
