name       : kdiagram
version    : 2.6.0
release    : 1
source     :
    - https://download.kde.org/stable/kdiagram/2.6.0/src/kdiagram-2.6.0.tar.xz : 02788dad7e15c64b74a2d1073c5910469ab4cf46ba905030c1713dce45981882
license    : GPL-2.0
component  : desktop.library
summary    : Powerful libraries (KChart, KGantt) for creating business diagrams.
description: |
    Powerful libraries (KChart, KGantt) for creating business diagrams.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
